#!/usr/bin/env bash
# =============================================================================
# scripts/verify-release-artifacts.sh
# -----------------------------------------------------------------------------
# THIN ORCHESTRATOR. Verifies the 10 canonical stable (-prod) images by
# delegating every per-image trust check to the single authoritative verifier
# scripts/verify-image-release-identity.sh (signature, exact per-role identity,
# issuer, SBOM, SLSA provenance, provenance repo+revision, OCI revision label,
# amd64+arm64). No verification logic is reimplemented here — this file only
# fans out over the matrix, pins each tag to its digest, and enforces 10/10.
#
# After the loop it writes a machine-readable results file (RESULTS_JSON) with
# per-check-class pass counts, REAL counts observed in the loop — the release
# evidence package derives its verification fields from this file instead of
# hardcoded literals (RA-01/WF-02).
#
# Env:
#   EXPECTED_REVISION  40-hex release revision (required unless LOCAL=1)
#   EXPECTED_REPO      default zenchron-dynamics/zenchron-foundry
#   EXPECTED_ROLE      default rc-publisher (stable digests are promoted RC digests)
#   REGISTRY/NAMESPACE default ghcr.io / zenchron-dynamics
#   RESULTS_JSON       results file path (default release-verify-results.json)
#   LOCAL=1            cosign/registry absent -> SKIP, exit 0
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
# shellcheck source=lib/common.sh
. "$ROOT/scripts/lib/common.sh"

REGISTRY="${REGISTRY:-ghcr.io}"; NAMESPACE="${NAMESPACE:-zenchron-dynamics}"
NS="${REGISTRY}/${NAMESPACE}"
VERIFIER="$ROOT/scripts/verify-image-release-identity.sh"
RESULTS_JSON="${RESULTS_JSON:-release-verify-results.json}"

# Stable -prod ref per matrix image.
stable_ref() { # <fam> <sel>
  case "$2" in prod) printf '%s/%s:prod' "$NS" "$1" ;; *) printf '%s/%s:%s-prod' "$NS" "$1" "$2" ;; esac
}
digest_of() { docker buildx imagetools inspect "$1" --format '{{.Manifest.Digest}}' 2>/dev/null; }

# The verifier runs its checks in a FIXED order and fails fast, so its failure
# message tells us exactly how many check classes the image really passed:
#   0=none  1=signature  2=+sbom  3=+provenance  4=+oci_revision  (5=all incl. arch)
# Unknown failure text credits NOTHING (fail closed).
classify_pass_count() { # <verifier stderr> -> 0..4
  case "$1" in
    *"signature/identity/issuer"*)  echo 0 ;;
    *"SBOM attestation"*)           echo 1 ;;
    *"provenance attestation"*|*"provenance predicate"*|*"no source revision"*|\
    *"provenance revision"*|*"provenance repo"*) echo 2 ;;
    *"OCI revision label"*|*"image config"*)     echo 3 ;;
    *"missing platform"*|*"image index"*)        echo 4 ;;
    *) echo 0 ;;
  esac
}

c_sig=0 c_sbom=0 c_prov=0 c_oci=0 c_arch=0
credit() { # <classes-passed 0..5>
  if [ "$1" -ge 1 ]; then c_sig=$((c_sig+1)); fi
  if [ "$1" -ge 2 ]; then c_sbom=$((c_sbom+1)); fi
  if [ "$1" -ge 3 ]; then c_prov=$((c_prov+1)); fi
  if [ "$1" -ge 4 ]; then c_oci=$((c_oci+1)); fi
  if [ "$1" -ge 5 ]; then c_arch=$((c_arch+1)); fi
}

write_results() { # <path> <images>
  command -v jq >/dev/null 2>&1 || die "jq required to write $1"
  jq -n --argjson n "$2" \
    --arg sig "$c_sig/$2" --arg sbom "$c_sbom/$2" --arg prov "$c_prov/$2" \
    --arg oci "$c_oci/$2" --arg arch "$c_arch/$2" \
    '{images: $n, signature: $sig, sbom: $sbom, provenance: $prov,
      oci_revision: $oci, architecture: $arch}' > "$1"
}

# --- self-test (offline: classification + results emission only) -------------
_vra_self_test() {
  command -v jq >/dev/null 2>&1 || { echo "SKIP - jq absent"; return 0; }
  local fail=0 tmp; tmp="$(mktemp -d)"
  _t() { if [ "$2" = "$3" ]; then echo "ok   - $1"; else echo "FAIL - $1: got '$2' want '$3'"; fail=1; fi; }
  # Fixture messages are HARDCODED (not generated by the verifier) on purpose.
  _t "sig failure credits nothing"   "$(classify_pass_count 'IDENTITY FAIL [x]: signature/identity/issuer verify failed')" 0
  _t "sbom failure credits sig"      "$(classify_pass_count 'IDENTITY FAIL [x]: SBOM attestation missing/invalid')" 1
  _t "prov attest credits sig+sbom"  "$(classify_pass_count 'IDENTITY FAIL [x]: provenance attestation missing/invalid')" 2
  _t "prov revision credits 2"       "$(classify_pass_count 'IDENTITY FAIL [x]: provenance revision aaa != expected bbb')" 2
  _t "oci label credits 3"           "$(classify_pass_count "IDENTITY FAIL [x]: OCI revision label '' != expected bbb")" 3
  _t "platform credits 4"            "$(classify_pass_count 'IDENTITY FAIL [x]: missing platform linux/arm64')" 4
  _t "unknown text credits nothing"  "$(classify_pass_count 'something unexpected exploded')" 0
  # results emission: partial counts survive verbatim (9/10 stays 9/10)
  c_sig=9 c_sbom=10 c_prov=10 c_oci=10 c_arch=10
  write_results "$tmp/r.json" 10
  _t "results images count"       "$(jq -r '.images' "$tmp/r.json")" 10
  _t "results partial signature"  "$(jq -r '.signature' "$tmp/r.json")" "9/10"
  _t "results sbom"               "$(jq -r '.sbom' "$tmp/r.json")" "10/10"
  _t "results provenance"         "$(jq -r '.provenance' "$tmp/r.json")" "10/10"
  _t "results oci_revision"       "$(jq -r '.oci_revision' "$tmp/r.json")" "10/10"
  _t "results architecture"       "$(jq -r '.architecture' "$tmp/r.json")" "10/10"
  c_sig=0 c_sbom=0 c_prov=0 c_oci=0 c_arch=0
  rm -rf "$tmp"; return $fail
}

case "${1:-}" in
  --self-test) _vra_self_test && echo "verify-release-artifacts.sh: SELF-TEST OK"; exit ;;
esac

export EXPECTED_REPO="${EXPECTED_REPO:-zenchron-dynamics/zenchron-foundry}"
export EXPECTED_ROLE="${EXPECTED_ROLE:-rc-publisher}"

if [ "${LOCAL:-0}" = 1 ] || ! command -v cosign >/dev/null 2>&1; then
  [ "${LOCAL:-0}" = 1 ] || die "cosign not installed (set LOCAL=1 to skip for non-release use)"
  echo "SKIPPED: LOCAL=1 — release artifact verification not run"; exit 0
fi
[ -n "${EXPECTED_REVISION:-}" ] || die "EXPECTED_REVISION required (40-hex release revision)"
export EXPECTED_REVISION

n=0 ok=0
for t in $MATRIX_IMAGES; do
  n=$((n+1)); fam="${t%:*}"; sel="${t#*:}"
  ref="$(stable_ref "$fam" "$sel")"
  dg="$(digest_of "$ref" || true)"
  [ -n "$dg" ] || { echo "FAIL $ref: digest unresolved"; continue; }
  if out="$("$VERIFIER" "${NS}/${fam}@${dg}" 2>&1)"; then
    echo "PASS $ref @ $dg"; ok=$((ok+1)); credit 5
  else
    echo "FAIL $ref @ $dg (identity verification failed)"
    credit "$(classify_pass_count "$out")"
  fi
done

# Machine-readable per-class results — written even when the gate below dies,
# so a partial run leaves honest counts (e.g. 9/10) that the evidence
# validator will REFUSE.
write_results "$RESULTS_JSON" "$n"
echo "wrote $RESULTS_JSON (signature=$c_sig/$n sbom=$c_sbom/$n provenance=$c_prov/$n oci_revision=$c_oci/$n architecture=$c_arch/$n)"

echo "RELEASE VERIFY: ${ok}/${n} images fully verified"
assert_full_matrix "$n"
[ "$ok" -eq "$MATRIX_COUNT" ] || die "not all images passed (${ok}/${MATRIX_COUNT})"
echo "ALL CHECKS PASSED (${MATRIX_COUNT}/${MATRIX_COUNT})"
